// <auto-generated />
using System;
using FinalProjectAmPlansForLoans.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectAmPlansForLoans.DataAccess.Migrations
{
    [DbContext(typeof(AmPlansDbContext))]
    partial class AmPlansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.AmPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Expense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FirstInstallmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Installments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanInputID")
                        .HasColumnType("int");

                    b.Property<int>("NoInstallment")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanInputID");

                    b.HasIndex("ProductID");

                    b.ToTable("AmPlans", (string)null);
                });

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.LoanInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdminFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstInstallmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("LoanInputs", (string)null);
                });

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdminFee")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxAmount")
                        .HasColumnType("float");

                    b.Property<double>("MaxInterestRate")
                        .HasColumnType("float");

                    b.Property<int>("MaxNumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<double>("MinAmount")
                        .HasColumnType("float");

                    b.Property<double>("MinInterestRate")
                        .HasColumnType("float");

                    b.Property<int>("MinNumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminFee = 0.0,
                            Description = "Standard home financing",
                            MaxAmount = 100000.0,
                            MaxInterestRate = 5.5,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 10000.0,
                            MinInterestRate = 2.0,
                            MinNumberOfInstallments = 10,
                            ProductName = "Home Loan",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AdminFee = 1500.0,
                            Description = "Standard Agro financing",
                            MaxAmount = 500000.0,
                            MaxInterestRate = 4.5,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 10000.0,
                            MinInterestRate = 3.0,
                            MinNumberOfInstallments = 10,
                            ProductName = "Agro Loan",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AdminFee = 2000.0,
                            Description = "Financing for vehicles",
                            MaxAmount = 50000.0,
                            MaxInterestRate = 4.5,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 2000.0,
                            MinInterestRate = 2.5,
                            MinNumberOfInstallments = 10,
                            ProductName = "Auto Loan",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AdminFee = 500.0,
                            Description = "Financing for Education",
                            MaxAmount = 15000.0,
                            MaxInterestRate = 3.5,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 5000.0,
                            MinInterestRate = 2.0,
                            MinNumberOfInstallments = 10,
                            ProductName = "Education Loan",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AdminFee = 600.0,
                            Description = "Unsecured personal financing",
                            MaxAmount = 7000.0,
                            MaxInterestRate = 5.5,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 1500.0,
                            MinInterestRate = 2.0,
                            MinNumberOfInstallments = 10,
                            ProductName = "Personal Loan",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            AdminFee = 3500.0,
                            Description = "Standard business financing",
                            MaxAmount = 500000.0,
                            MaxInterestRate = 7.0,
                            MaxNumberOfInstallments = 60,
                            MinAmount = 30000.0,
                            MinInterestRate = 3.5,
                            MinNumberOfInstallments = 10,
                            ProductName = "Business Loan",
                            Status = 1
                        });
                });

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.AmPlan", b =>
                {
                    b.HasOne("FinalProjectAmPlansForLoans.Domain.Models.LoanInput", "LoanInput")
                        .WithMany("AmortizationPlans")
                        .HasForeignKey("LoanInputID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectAmPlansForLoans.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanInput");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.LoanInput", b =>
                {
                    b.HasOne("FinalProjectAmPlansForLoans.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FinalProjectAmPlansForLoans.Domain.Models.LoanInput", b =>
                {
                    b.Navigation("AmortizationPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
